FROM node:8.9.3
##安装node相关依赖
RUN \
npm install yarn -g \
yarn global add nrm && \
nrm use taobao &&\
yarn global add @antv/data-set@0.10.1 &&\
yarn global add @babel/runtime@7.3.1 &&\
yarn global add antd@3.16.2
